/*
 * MeasureToolListener.java
 *
 * Created on April 22, 2005, 2:47 PM
 */

package ika.map.tools;

import ika.gui.MapComponent;

/**
 * MeasureToolListener - a listener for events generated by a MeasureTool.
 * @author Bernhard Jenny, Institute of Cartography, ETH Zurich.
 */
public interface MeasureToolListener {
   
    /**
     * The measure tool has been moved on the map. Update distance and angle.
     * @param x1 drag start x
     * @param y1 drag start y
     * @param x2 drag end x
     * @param y2 drag end y
     * @param mapComponent map
     */
   void updateMeasureTool(double x1, double y1, double x2, double y2, MapComponent mapComponent);

   /**
    * The mouse has been released, the line is therefore not visible anymore
    * in the map.
    */
   void clearDistance();
}
